import { colors, fonts } from "./tokens";

const lc = (hex: string): string => hex.toLowerCase();

/**
 * Render the canonical Saerens `:root` custom properties consumed by the web
 * artifacts (their Tailwind v4 `@theme inline` block maps these `--slide-*`
 * vars). This function is the source; `brand.css` is generated from it and
 * committed. Never hand-edit `brand.css`.
 */
export function renderBrandCss(): string {
  return `/* GENERATED by @workspace/brand — run \`pnpm --filter @workspace/brand run generate\`. Do not edit by hand. */
:root {
  --slide-primary: ${lc(colors.purple)};
  --slide-accent: ${lc(colors.amber)};
  --slide-bg: ${lc(colors.panel)};
  --slide-text: ${lc(colors.ink)};
  --slide-muted: ${lc(colors.muted)};
  --slide-nearblack: ${lc(colors.nearblack)};
  --slide-indigo: ${lc(colors.indigo)};
  --slide-hair: ${lc(colors.hair)};
  --slide-card-dark: ${lc(colors.cardDark)};
  --slide-card-label: ${lc(colors.cardLabel)};
  --slide-white: ${lc(colors.white)};
  --font-display-family: ${fonts.displayStack};
  --font-body-family: ${fonts.bodyStack};
  color-scheme: light;
}
`;
}
