import { useEffect, useMemo, useRef, useState } from "react";
import { Link, useLocation, useSearch } from "wouter";
import { useQueryClient } from "@tanstack/react-query";
import {
  getGetDocGraphQueryKey, getGetTeamQueryKey, useGetAgentRuns, useGetAgentStats,
  useGetDocGraph, useGetTeam, useUpdateAgentPersona, useUploadAgentPortrait,
  type AgentRun, type TeamMember,
} from "@workspace/api-client-react";
import { Activity, AlertTriangle, ArrowRight, Bot, Camera, Check, ChevronRight, Loader2, PauseCircle, PlayCircle, Save, Search, Settings2, X } from "lucide-react";
import AtlasShell from "@/components/atlas/AtlasShell";
import "./AtlasAgents.css";

type PersonaKey = "personality" | "communicationStyle" | "caresMostAbout" | "signatureHabit" | "culturalFitNote";
type PersonaForm = Record<PersonaKey, string> & { name: string; oneLiner: string; roleSummary: string };
const personaFields: { key: PersonaKey; label: string }[] = [{ key: "personality", label: "Personality" }, { key: "communicationStyle", label: "Communication" }, { key: "caresMostAbout", label: "Cares most about" }, { key: "signatureHabit", label: "Signature habit" }, { key: "culturalFitNote", label: "Cultural fit" }];
const formFrom = (member: TeamMember): PersonaForm => ({ name: member.name ?? "", oneLiner: member.oneLiner ?? "", roleSummary: member.roleSummary ?? "", personality: member.personality ?? "", communicationStyle: member.communicationStyle ?? "", caresMostAbout: member.caresMostAbout ?? "", signatureHabit: member.signatureHabit ?? "", culturalFitNote: member.culturalFitNote ?? "" });
const formatDuration = (ms: number | null) => ms == null ? "Unknown" : ms < 60_000 ? `${Math.round(ms / 1000)} sec` : `${Math.round(ms / 60_000)} min`;
const formatDate = (value: string | null) => value ? new Intl.DateTimeFormat("en-BE", { day: "2-digit", month: "short", year: "numeric" }).format(new Date(value)) : "Never";
const initials = (member: TeamMember) => (member.name ?? member.title).split(/\s+/).slice(0, 2).map((part) => part[0]).join("").toUpperCase();
const fileData = (file: File) => new Promise<string>((resolve, reject) => { const reader = new FileReader(); reader.onload = () => resolve(String(reader.result)); reader.onerror = () => reject(reader.error); reader.readAsDataURL(file); });

function Portrait({ member, large = false }: { member: TeamMember; large?: boolean }) { const src = member.portraitThumbUrl ?? member.portraitUrl; return src ? <img className={large ? "agents-portrait is-large" : "agents-portrait"} src={src} alt={member.name ?? member.title} /> : <i className={large ? "agents-portrait is-large" : "agents-portrait"}>{initials(member)}</i>; }

function AgentInspector({ member, close }: { member: TeamMember; close: () => void }) {
  const queryClient = useQueryClient(); const fileRef = useRef<HTMLInputElement>(null);
  const stats = useGetAgentStats(member.slug); const runs = useGetAgentRuns(member.slug); const update = useUpdateAgentPersona(); const upload = useUploadAgentPortrait();
  const [editing, setEditing] = useState(false); const [form, setForm] = useState(() => formFrom(member)); const [error, setError] = useState<string | null>(null);
  useEffect(() => { setForm(formFrom(member)); setEditing(false); setError(null); }, [member]);
  const refresh = () => { queryClient.invalidateQueries({ queryKey: getGetTeamQueryKey() }); queryClient.invalidateQueries({ queryKey: getGetDocGraphQueryKey() }); };
  const save = async () => { setError(null); try { await update.mutateAsync({ slug: member.slug, data: form }); refresh(); setEditing(false); } catch (err) { setError(err instanceof Error ? err.message : "Configuration update failed"); } };
  const portrait = async (file?: File) => { if (!file) return; setError(null); try { await upload.mutateAsync({ slug: member.slug, data: { imageBase64: await fileData(file) } }); refresh(); } catch (err) { setError(err instanceof Error ? err.message : "Portrait upload failed"); } };
  const lifecycle = member.active ? "active" : "paused";
  return <section className="agents-inspector" data-lenis-prevent><header><div className="agents-identity"><div className="agents-portrait-wrap"><Portrait member={member} large /><input ref={fileRef} type="file" accept="image/png,image/jpeg,image/webp" hidden onChange={(event) => void portrait(event.target.files?.[0])} /><button type="button" onClick={() => fileRef.current?.click()} disabled={upload.isPending}>{upload.isPending ? <Loader2 className="atlas-rotating" /> : <Camera />}</button></div><span><small>{member.title}</small><h2>{member.name ?? member.title}</h2><p>{member.oneLiner || member.roleSummary || "No persona summary recorded."}</p></span></div><button type="button" onClick={close} aria-label="Close agent"><X /></button></header>
    <div className="agents-lifecycle" data-lifecycle={lifecycle}>{member.active ? <PlayCircle /> : <PauseCircle />}<span><small>Lifecycle</small><b>{lifecycle}</b><p>{member.active ? "Available to the Orchestrator and new routing." : "Excluded from new routing, retained for history and governance."}</p></span></div>
    <nav className="agents-inspector-actions"><button type="button" className={editing ? "is-active" : ""} onClick={() => setEditing((value) => !value)}><Settings2 />Persona configuration</button></nav>
    {editing ? <div className="agents-form"><div className="agents-form-warning"><AlertTriangle /><span><b>Canonical configuration change</b><p>This writes agent configuration. It is owner-only and must remain visible in repository history.</p></span></div>{(["name", "oneLiner", "roleSummary"] as const).map((key) => <label key={key}><span>{key === "oneLiner" ? "In one line" : key === "roleSummary" ? "Role summary" : "Name"}</span><textarea rows={key === "name" ? 1 : 3} value={form[key]} onChange={(event) => setForm((current) => ({ ...current, [key]: event.target.value }))} /></label>)}{personaFields.map(({ key, label }) => <label key={key}><span>{label}</span><textarea rows={2} value={form[key]} onChange={(event) => setForm((current) => ({ ...current, [key]: event.target.value }))} /></label>)}{error && <p className="agents-error"><AlertTriangle />{error}</p>}<div><button type="button" className="is-primary" disabled={update.isPending} onClick={() => void save()}>{update.isPending ? <Loader2 className="atlas-rotating" /> : <Save />}Save configuration</button><button type="button" onClick={() => setEditing(false)}>Cancel</button></div></div> : <div className="agents-dossier"><section><small>Persona</small><h3>Operating character</h3>{member.roleSummary && <p className="agents-role">{member.roleSummary}</p>}<dl>{personaFields.map(({ key, label }) => member[key] ? <div key={key}><dt>{label}</dt><dd>{member[key]}</dd></div> : null)}</dl></section><section><small>Performance context</small><h3>Runs and outcomes</h3>{stats.isLoading ? <Loader2 className="atlas-rotating" /> : stats.data ? <div className="agents-stats"><div><b>{stats.data.runsLed}</b><span>Runs led</span></div><div><b>{stats.data.runsParticipated}</b><span>Participated</span></div><div><b>{formatDuration(stats.data.avgDurationMs)}</b><span>Avg duration</span></div><div><b>{stats.data.approved}</b><span>Approved</span></div><div><b>{stats.data.rejected}</b><span>Rejected</span></div><div><b>{formatDate(stats.data.lastActiveAt)}</b><span>Last active</span></div></div> : <p className="agents-muted">Stats unavailable.</p>}<div className="agents-runs">{(runs.data?.runs ?? []).slice(0, 8).map((run: AgentRun) => <Link key={run.id} href={`/history?id=${run.id}`}><span><b>{run.clientName}</b><small>{run.workflowTitle} · {run.role}</small></span><ArrowRight /></Link>)}</div></section></div>}
  </section>;
}

export default function AtlasAgents() {
  const searchString = useSearch(); const [, navigate] = useLocation(); const team = useGetTeam(); useGetDocGraph();
  const [query, setQuery] = useState(""); const [lifecycle, setLifecycle] = useState<"active" | "paused" | "all">("active"); const [selectedSlug, setSelectedSlug] = useState<string | null>(new URLSearchParams(searchString).get("agent"));
  const employees = useMemo(() => [...(team.data?.employees ?? [])].sort((a, b) => (a.name ?? a.title).localeCompare(b.name ?? b.title)), [team.data]);
  const visible = useMemo(() => { const term = query.trim().toLowerCase(); return employees.filter((member) => (lifecycle === "all" || (lifecycle === "active" ? member.active : !member.active)) && (!term || member.title.toLowerCase().includes(term) || member.name?.toLowerCase().includes(term) || member.department.title.toLowerCase().includes(term))); }, [employees, query, lifecycle]);
  const selected = employees.find((member) => member.slug === selectedSlug) ?? null;
  const choose = (member: TeamMember) => { setSelectedSlug(member.slug); navigate(`/team?agent=${member.slug}`, { replace: true }); };
  return <AtlasShell title="Agents" subtitle="Active roster, dossiers and lifecycle governance"><main className="agents-stage"><aside className={`agents-index${selected ? " has-selection" : ""}`} data-lenis-prevent><div className="agents-search"><Search /><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search agents" /></div><div className="agents-filters">{(["active", "paused", "all"] as const).map((value) => <button key={value} type="button" className={lifecycle === value ? "is-active" : ""} onClick={() => setLifecycle(value)}>{value}</button>)}</div><div className="agents-index-meta"><span>{visible.length} agents</span><span>{lifecycle}</span></div>{team.isLoading && <div className="agents-state"><Loader2 className="atlas-rotating" />Loading roster</div>}{team.isError && <div className="agents-state is-error"><AlertTriangle />Roster unavailable</div>}<div className="agents-list">{visible.map((member) => <button key={member.slug} type="button" className={selectedSlug === member.slug ? "is-active" : ""} onClick={() => choose(member)}><Portrait member={member} /><span><b>{member.name ?? member.title}</b><small>{member.title}</small><p>{member.department.title}</p></span><i data-active={member.active} title={member.active ? "Active" : "Paused"} /><ChevronRight /></button>)}</div></aside>{selected ? <AgentInspector member={selected} close={() => { setSelectedSlug(null); navigate("/team", { replace: true }); }} /> : <section className="agents-empty"><Bot /><h2>Select an agent</h2><p>Active agents route by default. Paused agents remain available for history and governance.</p></section>}</main></AtlasShell>;
}
