import { useQuery } from "@tanstack/react-query";
import { Link } from "wouter";
import { getAtlasOperationsStatus,getAtlasSystemStatus,type HealthState,type SystemCheck } from "@workspace/api-client-react";
import { Activity,AlertTriangle,ArrowUpRight,CheckCircle2,Clock3,Database,GitCommit,Loader2,RefreshCw,Server,ShieldCheck,Webhook,Workflow } from "lucide-react";
import AtlasShell from "@/components/atlas/AtlasShell";import "./Operations.css";
const iconFor=(key:string)=>key.includes("database")||key.includes("store")||key==="db"?<Database/>:key.includes("clickup")||key.includes("webhook")?<Webhook/>:key.includes("scheduler")||key.includes("queue")?<Workflow/>:key.includes("build")?<GitCommit/>:<Server/>;const labelFor=(key:string)=>key.replaceAll("_"," ").replaceAll("-"," ").replace(/\b\w/g,(letter)=>letter.toUpperCase());const formatDate=(value:string|null|undefined)=>value?new Intl.DateTimeFormat("en-BE",{day:"2-digit",month:"short",hour:"2-digit",minute:"2-digit",second:"2-digit"}).format(new Date(value)):"Not recorded";const tone=(state:HealthState|string)=>state==="healthy"||state==="match"?"healthy":state==="degraded"||state==="mismatch"?"attention":state==="down"?"danger":"unknown";const shortSha=(value:string|null|undefined)=>value?value.slice(0,10):"Unknown";const recovery=(key:string)=>key.includes("scheduler")?"/todo/schedules":key.includes("webhook")||key.includes("queue")?"/todo":key==="graph"?"/":"/todo";
function CheckRow({check}:{check:SystemCheck}){const actionable=check.status==="down"||check.status==="degraded";return <div className="health-check-row" data-tone={tone(check.status)}><i>{iconFor(check.key)}</i><span><small>{check.key}</small><b>{labelFor(check.key)}</b><p>{check.message||`Checked ${formatDate(check.checkedAt)}`}</p></span>{actionable?<Link href={recovery(check.key)} aria-label={`Open recovery for ${labelFor(check.key)}`}><ArrowUpRight/></Link>:<time>{typeof check.latencyMs==="number"?`${check.latencyMs} ms`:check.status}</time>}</div>}
export default function SystemHealth(){const system=useQuery({queryKey:["atlas-system-status"],queryFn:({signal})=>getAtlasSystemStatus(signal),refetchInterval:30_000});const operations=useQuery({queryKey:["atlas-operations-status"],queryFn:({signal})=>getAtlasOperationsStatus(signal),refetchInterval:30_000});const refresh=()=>{void system.refetch();void operations.refetch()};const actions=<button type="button" className="atlas-action" onClick={refresh} disabled={system.isFetching||operations.isFetching}><RefreshCw className={system.isFetching||operations.isFetching?"atlas-rotating":""}/>Refresh checks</button>;const overall=system.data?.status??"unknown";const checkedAt=system.data?.checks.map((check)=>check.checkedAt).sort().at(-1);const provenance=system.data?.provenance;const compatibility=system.data?.compatibility;const schedulerDurable=operations.data?.scheduler.durable;const webhookDurable=operations.data?.webhook.durable;
return <AtlasShell title="System Health" subtitle="Truthful runtime status, no vanity uptime" actions={actions}><main className="health-stage" data-lenis-prevent><header className="health-overview" data-tone={tone(overall)}><div><p>Current state</p><h2>{overall==="healthy"?"All critical systems operational":overall==="degraded"?"Service is degraded":overall==="down"?"Critical service interruption":"Health has not been verified"}</h2><span><Clock3/>Last verified {formatDate(checkedAt)}</span></div><i>{overall==="healthy"?<CheckCircle2/>:overall==="unknown"?<Activity/>:<AlertTriangle/>}</i></header>
{(system.isLoading||operations.isLoading)&&<div className="health-loading"><Loader2 className="atlas-rotating"/><p>Running independent checks</p></div>}{system.isError&&<div className="operations-error"><AlertTriangle/><span><b>System status unavailable</b><p>This is unknown health, not healthy. Check the API process directly before relying on automation.</p></span><button type="button" onClick={()=>system.refetch()}>Try again</button></div>}{compatibility?.status==="mismatch"&&<div className="operations-error"><AlertTriangle/><span><b>Frontend and API builds do not match</b><p>Frontend {shortSha(compatibility.frontendSha)} is connected to API {shortSha(compatibility.apiSha)}. Rebuild and restart both workflows before trusting automation.</p></span></div>}
{provenance&&<section className="health-runtime"><header><p>Runtime identity</p><h2>Deployed build</h2></header><div className="health-runtime-grid"><article data-tone={tone(compatibility?.status??"unknown")}><GitCommit/><small>Build compatibility</small><b>{compatibility?.status??"Unknown"}</b><p>Frontend {shortSha(compatibility?.frontendSha)} · API {shortSha(compatibility?.apiSha)}</p><span>Manifest {shortSha(provenance.manifestHash)}</span></article><article data-tone={provenance.manifestPresent?"healthy":"attention"}><Server/><small>API runtime</small><b>{provenance.deploymentMode}</b><p>{provenance.docsMode} docs · manifest v{provenance.version}</p><span>Started {formatDate(provenance.processStartedAt)}</span></article><article data-tone={provenance.docsHash?"healthy":"unknown"}><ShieldCheck/><small>Canonical package</small><b>{Object.values(provenance.counts).reduce<number>((sum,count)=>sum+count,0)} sources</b><p>Docs {shortSha(provenance.docsHash)}</p><span>Built {formatDate(provenance.builtAt)}</span></article></div></section>}
{system.data&&<section className="health-checks"><header><p>Independent checks</p><h2>Runtime services</h2><span>{system.data.checks.length} checks</span></header><div>{system.data.checks.map((check)=><CheckRow key={check.key} check={check}/>)}</div></section>}
<section className="health-runtime"><header><p>Durable evidence</p><h2>Automation layer</h2></header><div className="health-runtime-grid"><article data-tone={tone(schedulerDurable?.status??"unknown")}><Workflow/><small>Scheduler worker</small><b>{schedulerDurable?.status??"Unknown"}</b><p>{operations.data?.scheduler.enabledSchedules??0} enabled schedules</p><span>DB heartbeat {formatDate(operations.data?.scheduler.durableHeartbeatAt)}</span></article><article data-tone={tone(webhookDurable?.status??"unknown")}><Webhook/><small>Webhook worker</small><b>{webhookDurable?.status??"Unknown"}</b><p>{operations.data?.webhook.deadLetters??0} dead letters</p><span>DB heartbeat {formatDate(operations.data?.webhook.durableHeartbeatAt)}</span></article><article data-tone={(operations.data?.pushQueue.deadLetters??operations.data?.pushQueue.failed??0)>0?"danger":(operations.data?.pushQueue.retrying??0)>0?"attention":"healthy"}><ShieldCheck/><small>Delivery queue</small><b>{operations.data?.pushQueue.retrying??0} retrying</b><p>{operations.data?.pushQueue.deadLetters??operations.data?.pushQueue.failed??0} terminal failures</p><span>{operations.data?.pushQueue.pending??operations.data?.pushQueue.queued??0} waiting</span></article></div></section></main></AtlasShell>}
