import { Cron } from "croner";
import { logger } from "./logger";
import { resolveGenerationContext, runGeneration } from "./generate-engine";
import { claim, listDue, markRun } from "./schedules-store";
import { startInboundPoller } from "./email-inbound";
import { recordAlert } from "./alerts-store";
import type { Schedule as ScheduleRow } from "@workspace/db";
import { markSchedulerStarted,markSchedulerTickFailed,markSchedulerTickFinished,markSchedulerTickStarted,newCorrelationId,schedulerStatus } from "./runtime-observability";
import { touchWorkerHeartbeat } from "./worker-heartbeats";
const TICK_INTERVAL_MS=60_000;
export function computeNextRun(cronExpr:string,timezone:string,from:Date=new Date()):Date|null{try{return new Cron(cronExpr,{timezone}).nextRun(from)}catch{return null}}
export function isValidCron(cronExpr:string,timezone:string):boolean{try{new Cron(cronExpr,{timezone});return true}catch{return false}}
export function getSchedulerStatus(){return schedulerStatus()}
async function fire(schedule:ScheduleRow,correlationId:string):Promise<void>{let additional:string[]=[];try{const parsed=JSON.parse(schedule.additionalAgentPaths);if(Array.isArray(parsed))additional=parsed.filter((p):p is string=>typeof p==="string")}catch{additional=[]}const resolved=await resolveGenerationContext({agentPath:schedule.agentPath,additionalAgentPaths:additional,clientPath:schedule.clientPath,workflowPath:schedule.workflowPath,request:schedule.request});if(!resolved.ok){logger.warn({scheduleId:schedule.id,correlationId,error:resolved.error},"Scheduled run could not resolve its context");void recordAlert({source:"scheduler",severity:"error",message:`Geplande run kon zijn context niet opbouwen (planning #${schedule.id}).`,context:{key:`schedule:${schedule.id}`,scheduleId:schedule.id,correlationId,error:String(resolved.error??"onbekende fout").slice(0,500)}});await markRun(schedule.id,{lastGenerationId:null,lastStatus:"failed"});return}const result=await runGeneration(resolved.ctx,{sink:()=>{},signal:new AbortController().signal,triggerSource:"scheduled"});await markRun(schedule.id,{lastGenerationId:result.generationId??null,lastStatus:result.status});logger.info({scheduleId:schedule.id,generationId:result.generationId,correlationId,status:result.status},"Scheduled run finished")}
let ticking=false;async function tick():Promise<void>{if(ticking)return;ticking=true;markSchedulerTickStarted();void touchWorkerHeartbeat("scheduler","running",{force:true});try{const now=new Date(),due=await listDue(now);for(const schedule of due){if(!schedule.nextRunAt)continue;const next=computeNextRun(schedule.cronExpr,schedule.timezone,now),won=await claim(schedule.id,schedule.nextRunAt,next);if(!won)continue;const correlationId=newCorrelationId(`schedule-${schedule.id}`);try{await fire(schedule,correlationId)}catch(err){logger.error({err,scheduleId:schedule.id,correlationId},"Scheduled run threw unexpectedly");void recordAlert({source:"scheduler",severity:"error",message:`Geplande run mislukte (planning #${schedule.id}).`,context:{key:`schedule:${schedule.id}`,scheduleId:schedule.id,correlationId,error:(err instanceof Error?err.message:String(err)).slice(0,500)}});await markRun(schedule.id,{lastGenerationId:null,lastStatus:"failed"}).catch(()=>{})}}markSchedulerTickFinished();void touchWorkerHeartbeat("scheduler","healthy",{success:true,force:true,metadata:{dueCount:due.length}})}catch(err){markSchedulerTickFailed("SCHEDULER_TICK_FAILED");void touchWorkerHeartbeat("scheduler","failed",{errorCode:"SCHEDULER_TICK_FAILED",force:true});logger.error({err},"Scheduler tick failed");void recordAlert({source:"scheduler",severity:"error",message:"Planner-tik mislukte (geplande runs zijn mogelijk overgeslagen).",context:{key:"scheduler-tick",error:(err instanceof Error?err.message:String(err)).slice(0,500)}})}finally{ticking=false}}
export function startScheduler():void{markSchedulerStarted();void touchWorkerHeartbeat("scheduler","starting",{force:true});logger.info({intervalMs:TICK_INTERVAL_MS},"Scheduler started");setTimeout(()=>void tick(),5000);setInterval(()=>void tick(),TICK_INTERVAL_MS);startInboundPoller()}
