import { pool } from "@workspace/db";
import { logger } from "./logger";
export type WorkerName="scheduler"|"clickup-webhook";export type WorkerHeartbeatStatus="starting"|"idle"|"running"|"healthy"|"failed";export interface WorkerHeartbeat{name:WorkerName;instanceId:string;status:WorkerHeartbeatStatus;heartbeatAt:string;startedAt:string;lastSuccessAt:string|null;lastErrorAt:string|null;lastErrorCode:string|null;metadata:Record<string,unknown>}
const instanceId=`${process.env.REPL_ID??"local"}:${process.pid}:${Date.now()}`;let ready:Promise<boolean>|null=null;const lastWrite=new Map<WorkerName,number>();
async function ensureTable():Promise<boolean>{if(!ready)ready=pool.query(`CREATE TABLE IF NOT EXISTS worker_heartbeats (worker_name text PRIMARY KEY,instance_id text NOT NULL,status text NOT NULL,heartbeat_at timestamptz NOT NULL,started_at timestamptz NOT NULL,last_success_at timestamptz,last_error_at timestamptz,last_error_code text,metadata jsonb NOT NULL DEFAULT '{}'::jsonb)`).then(()=>true).catch((error)=>{ready=null;logger.warn({scope:"health:heartbeat",err:error instanceof Error?error.message:String(error)},"worker heartbeat store unavailable");return false});return ready}
export async function touchWorkerHeartbeat(name:WorkerName,status:WorkerHeartbeatStatus,input:{success?:boolean;errorCode?:string|null;metadata?:Record<string,unknown>;force?:boolean}={}):Promise<void>{const now=Date.now();if(!input.force&&now-(lastWrite.get(name)??0)<15_000)return;if(!await ensureTable())return;lastWrite.set(name,now);const errorCode=input.errorCode?.slice(0,120)??null;await pool.query(`INSERT INTO worker_heartbeats (worker_name,instance_id,status,heartbeat_at,started_at,last_success_at,last_error_at,last_error_code,metadata) VALUES ($1,$2,$3,now(),now(),CASE WHEN $4 THEN now() ELSE NULL END,CASE WHEN $5::text IS NOT NULL THEN now() ELSE NULL END,$5,$6::jsonb) ON CONFLICT (worker_name) DO UPDATE SET instance_id=EXCLUDED.instance_id,status=EXCLUDED.status,heartbeat_at=now(),started_at=CASE WHEN worker_heartbeats.instance_id<>EXCLUDED.instance_id THEN now() ELSE worker_heartbeats.started_at END,last_success_at=CASE WHEN $4 THEN now() ELSE worker_heartbeats.last_success_at END,last_error_at=CASE WHEN $5::text IS NOT NULL THEN now() ELSE worker_heartbeats.last_error_at END,last_error_code=CASE WHEN $5::text IS NOT NULL THEN $5 ELSE worker_heartbeats.last_error_code END,metadata=EXCLUDED.metadata`,[name,instanceId,status,Boolean(input.success),errorCode,JSON.stringify(input.metadata??{})]).catch((error)=>logger.warn({scope:"health:heartbeat",name,err:error instanceof Error?error.message:String(error)},"worker heartbeat write failed"))}
const iso=(value:unknown):string|null=>value==null?null:(value instanceof Date?value:new Date(String(value))).toISOString();
export async function readWorkerHeartbeats():Promise<WorkerHeartbeat[]>{if(!await ensureTable())return[];const result=await pool.query(`SELECT * FROM worker_heartbeats ORDER BY worker_name`);return result.rows.map((row)=>({name:String(row.worker_name)as WorkerName,instanceId:String(row.instance_id),status:String(row.status)as WorkerHeartbeatStatus,heartbeatAt:iso(row.heartbeat_at)!,startedAt:iso(row.started_at)!,lastSuccessAt:iso(row.last_success_at),lastErrorAt:iso(row.last_error_at),lastErrorCode:row.last_error_code==null?null:String(row.last_error_code),metadata:row.metadata&&typeof row.metadata==="object"?row.metadata as Record<string,unknown>:{}}))}
export function classifyHeartbeat(heartbeat:WorkerHeartbeat|undefined,now=Date.now(),staleAfterMs=180_000){if(!heartbeat)return{status:"unknown"as const,ageMs:null,message:"HEARTBEAT_NOT_RECORDED"};const ageMs=Math.max(0,now-Date.parse(heartbeat.heartbeatAt));if(heartbeat.status==="failed")return{status:"down"as const,ageMs,message:heartbeat.lastErrorCode??"WORKER_FAILED"};if(ageMs>staleAfterMs)return{status:"down"as const,ageMs,message:"HEARTBEAT_STALE"};return{status:"healthy"as const,ageMs,message:heartbeat.status.toUpperCase()}}
export interface RuntimeStoreReadiness{status:"healthy"|"degraded"|"down";checkedAt:string;required:Record<string,boolean>;optional:Record<string,boolean>;missingRequired:string[]}
export async function checkRuntimeStores():Promise<RuntimeStoreReadiness>{const requiredNames=["schedules","graph_snapshots","clickup_push_records","clickup_webhook_events","worker_heartbeats"];const optionalNames=["crawl_snapshots","semantic_embeddings"];const result=await pool.query(`SELECT name,to_regclass('public.'||name) IS NOT NULL AS present FROM unnest($1::text[]) AS stores(name)`,[[...requiredNames,...optionalNames]]);const found=new Map(result.rows.map((row)=>[String(row.name),Boolean(row.present)]));const required=Object.fromEntries(requiredNames.map((name)=>[name,found.get(name)??false]));const optional=Object.fromEntries(optionalNames.map((name)=>[name,found.get(name)??false]));const missingRequired=requiredNames.filter((name)=>!required[name]);return{status:missingRequired.length?"down":Object.values(optional).some((present)=>!present)?"degraded":"healthy",checkedAt:new Date().toISOString(),required,optional,missingRequired}}
export function resetWorkerHeartbeatStateForTests():void{ready=null;lastWrite.clear()}
