import { Router, type IRouter } from "express";
import { GetGraphOverviewResponse, GetGraphNeighborsResponse, SearchGraphResponse, SyncGraphResponse, GetGraphSyncStatusResponse } from "@workspace/api-zod";
import { isOwner } from "../middlewares/requireAuth";
import { buildGraph } from "../lib/graph/build";
import { collectGraphInput } from "../lib/graph/collect";
import { diagnoseGraph } from "../lib/graph/diagnostics";
import { diagnosticState, diagnosticsEqual, getGraphDiagnosticEvidence, setGraphDiagnosticEvidence } from "../lib/graph/diagnostic-state";
import { applyGovernanceProjection } from "../lib/graph/governance-projection";
import { applyHierarchyProjection } from "../lib/graph/hierarchy-projection";
import { neighbors, reduceToOverview, searchNodes } from "../lib/graph/overview";
import { beginSync, completeSync, failSync, getActiveGraph, isSyncing, loadActiveIntoMemory, type SnapshotMeta } from "../lib/graph/snapshot-store";
import { getRuntimeProvenance } from "../lib/runtime-provenance";
import { loadBrainGovernance } from "../lib/brain-governance";
import { loadBrainHierarchy } from "../lib/brain-hierarchy";
import { listDocFiles } from "../lib/docs";
import type { Graph } from "../lib/graph/types";
import type { GraphCollectionReport } from "../lib/graph/collection-policy";

const router: IRouter = Router(); const EMPTY_GRAPH: Graph = { nodes: [], edges: [] }; const unlimitedOverviewEnabled = () => process.env.GRAPH_OVERVIEW_UNLIMITED === "true";
function metaFrom(m: SnapshotMeta | null | undefined) { if (!m) return { status: "none", nodeCount: 0, edgeCount: 0, contentHash: null, sourceUpdatedAt: null, lastSyncedAt: null, error: null, syncing: isSyncing() }; return { status: m.status === "active" ? "active" : "none", nodeCount: m.nodeCount, edgeCount: m.edgeCount, contentHash: m.contentHash, sourceUpdatedAt: m.sourceUpdatedAt, lastSyncedAt: m.lastSyncedAt, error: m.error, syncing: isSyncing() }; }
async function readActive(): Promise<{ meta: SnapshotMeta; graph: Graph } | null> { return getActiveGraph() ?? (await loadActiveIntoMemory()); }
function exclusionCount(report: GraphCollectionReport | undefined): number { if (!report) return 0; return report.workspaces.excluded + report.spaces.excluded + report.lists.excluded + report.tasks.excludedByAge + report.tasks.excludedByListCap + report.tasks.excludedByGlobalCap + report.docs.excluded + report.pages.excluded + report.pushRecords.excluded; }
function wireEvidence() { const saved = getGraphDiagnosticEvidence(); if (!saved) return null; return { state: saved.state, checkedAt: saved.checkedAt, snapshotId: saved.snapshotId, contentHash: saved.contentHash, buildSha: saved.runtime.gitSha, manifestHash: saved.runtime.manifestHash, candidate: saved.candidate, active: saved.active, serialized: saved.serialized, sourceErrors: saved.sourceErrors, parity: saved.parity }; }
router.get("/graph/runtime-provenance", async (_req, res): Promise<void> => { const active = await readActive(); res.json({ runtime: getRuntimeProvenance(), active: active ? { snapshotId: active.meta.id, contentHash: active.meta.contentHash, diagnostics: diagnoseGraph(active.graph, getRuntimeProvenance()) } : null }); });
router.get("/graph/diagnostics", async (_req, res): Promise<void> => { const active = await readActive(); const runtime = getRuntimeProvenance(); const saved = wireEvidence(); if (saved) { res.json(saved); return; } const diagnostics = active ? diagnoseGraph(active.graph, runtime) : null; res.json({ state: diagnostics ? diagnosticState({ diagnostics, sourceErrors: [], parity: true }) : "unknown", checkedAt: new Date().toISOString(), snapshotId: active?.meta.id ?? null, contentHash: active?.meta.contentHash ?? null, buildSha: runtime.gitSha, manifestHash: runtime.manifestHash, candidate: null, active: diagnostics, serialized: diagnostics, sourceErrors: [], parity: { candidateToActive: null, activeToSerialized: diagnostics ? true : null } }); });
router.get("/graph/overview", async (_req, res): Promise<void> => { const active = await readActive(); const graph = active?.graph ?? EMPTY_GRAPH; const overview = unlimitedOverviewEnabled() ? { nodes: graph.nodes, edges: graph.edges, truncated: false, totalNodes: graph.nodes.length, totalEdges: graph.edges.length } : reduceToOverview(graph); const payload = GetGraphOverviewResponse.parse({ nodes: overview.nodes, edges: overview.edges, meta: metaFrom(active?.meta), truncated: overview.truncated, totalNodes: overview.totalNodes, totalEdges: overview.totalEdges }); const runtime = getRuntimeProvenance(); const serialized = diagnoseGraph(graph, runtime); const saved = getGraphDiagnosticEvidence(); if (active) setGraphDiagnosticEvidence({ state: saved?.state ?? diagnosticState({ diagnostics: serialized, sourceErrors: [], parity: true }), checkedAt: new Date().toISOString(), snapshotId: active.meta.id, contentHash: active.meta.contentHash, runtime, candidate: saved?.candidate ?? null, active: saved?.active ?? serialized, serialized, sourceErrors: saved?.sourceErrors ?? [], parity: { candidateToActive: saved?.parity.candidateToActive ?? null, activeToSerialized: diagnosticsEqual(saved?.active ?? serialized, serialized) } }); res.json(payload); });
router.get("/graph/neighbors/:nodeId", async (req, res): Promise<void> => { const active = await readActive(); const result = neighbors(active?.graph ?? EMPTY_GRAPH, req.params.nodeId); if (!result) { res.status(404).json({ error: "Node not found in the active snapshot" }); return; } res.json(GetGraphNeighborsResponse.parse({ center: result.center, nodes: result.nodes, edges: result.edges })); });
router.get("/graph/search", async (req, res): Promise<void> => { const q = typeof req.query.q === "string" ? req.query.q : ""; if (!q.trim()) { res.status(400).json({ error: "Query parameter 'q' is required" }); return; } const parsed = typeof req.query.limit === "string" ? Number.parseInt(req.query.limit, 10) : 30; const limit = Number.isFinite(parsed) ? Math.min(100, Math.max(1, parsed)) : 30; const active = await readActive(); res.json(SearchGraphResponse.parse(searchNodes(active?.graph ?? EMPTY_GRAPH, q, limit))); });
router.post("/graph/sync", async (req, res): Promise<void> => {
  if (!isOwner(req)) { res.status(403).json({ error: "Only the account owner can rebuild the graph" }); return; } if (isSyncing()) { res.status(409).json({ error: "A graph sync is already in progress" }); return; }
  const buildingId = await beginSync(); if (buildingId === null) { res.status(409).json({ error: "The graph store is busy or unavailable" }); return; }
  let candidateDiagnostics = null as ReturnType<typeof diagnoseGraph> | null; let sourceErrors: string[] = [];
  try {
    const collected = await collectGraphInput(); sourceErrors = collected.errors; if (!collected.ok) { await failSync(buildingId, collected.errors.join("; ").slice(0, 300) || "source crawl failed"); const runtime = getRuntimeProvenance(); setGraphDiagnosticEvidence({ state: "failed", checkedAt: new Date().toISOString(), snapshotId: getActiveGraph()?.meta.id ?? null, contentHash: getActiveGraph()?.meta.contentHash ?? null, runtime, candidate: null, active: getActiveGraph() ? diagnoseGraph(getActiveGraph()!.graph, runtime) : null, serialized: null, sourceErrors: collected.errors, parity: { candidateToActive: null, activeToSerialized: null } }); res.status(502).json(SyncGraphResponse.parse({ ok: false, changed: false, meta: metaFrom(getActiveGraph()?.meta), note: "Bronnen niet bereikbaar; vorige graph behouden." })); return; }
    const baseGraph = buildGraph(collected.input); let graph = baseGraph;
    if (collected.input.docGraph?.nodes) { const hierarchy = loadBrainHierarchy(listDocFiles().map((file) => file.path)); if (hierarchy.issues.length) throw new Error(`hierarchy invalid: ${hierarchy.issues.map((issue) => issue.code).join(",")}`); graph = applyHierarchyProjection(baseGraph, hierarchy); const governance = loadBrainGovernance(); if (governance.issues.length) throw new Error(`governance invalid: ${governance.issues.map((issue) => issue.code).join(",")}`); graph = applyGovernanceProjection(graph, governance); }
    const runtime = getRuntimeProvenance(); candidateDiagnostics = diagnoseGraph(graph, runtime); if (candidateDiagnostics.invariantFailures.length) throw new Error(`graph invariants: ${candidateDiagnostics.invariantFailures.join(",")}`);
    const { changed, meta } = await completeSync(buildingId, graph, { sourceUpdatedAt: collected.sourceUpdatedAt }); const active = getActiveGraph(); const activeDiagnostics = diagnoseGraph(active?.graph ?? EMPTY_GRAPH, runtime); const candidateToActive = Boolean(active && active.meta.contentHash === meta.contentHash && diagnosticsEqual(candidateDiagnostics, activeDiagnostics)); if (!candidateToActive) throw new Error("active graph diagnostics do not match candidate");
    setGraphDiagnosticEvidence({ state: diagnosticState({ diagnostics: activeDiagnostics, sourceErrors, parity: candidateToActive }), checkedAt: new Date().toISOString(), snapshotId: meta.id, contentHash: meta.contentHash, runtime, candidate: candidateDiagnostics, active: activeDiagnostics, serialized: null, sourceErrors, parity: { candidateToActive, activeToSerialized: null } });
    const excluded = exclusionCount(collected.report); const notes: string[] = []; if (excluded > 0) notes.push(`Begrensd: ${graph.nodes.length} nodes opgenomen, ${excluded} bronitems uitgesloten.`); if (sourceErrors.length > 0) notes.push(`Gedeeltelijk: ${sourceErrors.length} bron(nen) niet bereikbaar.`); notes.push(`Build ${runtime.gitSha?.slice(0, 8) ?? "unknown"}; lenses S${candidateDiagnostics.nodesByLens.structure} K${candidateDiagnostics.nodesByLens.knowledge} A${candidateDiagnostics.nodesByLens.agents} W${candidateDiagnostics.nodesByLens.active} F${candidateDiagnostics.nodesByLens.flows}.`); res.json(SyncGraphResponse.parse({ ok: true, changed, meta: metaFrom(meta), note: notes.join(" ") }));
  } catch (error) { await failSync(buildingId, error instanceof Error ? error.message : "sync failed"); const runtime = getRuntimeProvenance(); const active = getActiveGraph(); setGraphDiagnosticEvidence({ state: "failed", checkedAt: new Date().toISOString(), snapshotId: active?.meta.id ?? null, contentHash: active?.meta.contentHash ?? null, runtime, candidate: candidateDiagnostics, active: active ? diagnoseGraph(active.graph, runtime) : null, serialized: null, sourceErrors, parity: { candidateToActive: false, activeToSerialized: null } }); req.log.error({ err: error instanceof Error ? error.message : String(error), runtime }, "graph sync failed"); res.status(502).json(SyncGraphResponse.parse({ ok: false, changed: false, meta: metaFrom(active?.meta), note: `Sync mislukt op build ${runtime.gitSha?.slice(0, 8) ?? "unknown"}; vorige graph behouden.` })); }
});
router.get("/graph/sync-status", async (_req, res): Promise<void> => { const active = await readActive(); res.json(GetGraphSyncStatusResponse.parse({ meta: metaFrom(active?.meta) })); });
export default router;
