// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/genereren/EveningEdition.tsx": () => import("../components/mockups/genereren/EveningEdition.tsx"),
  "./components/mockups/genereren/Newsroom.tsx": () => import("../components/mockups/genereren/Newsroom.tsx")
};
